name: 📰 Blog posts to README
on:
  schedule: [{ cron: "15 2 * * *" }]
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@chiranjeetmishra13"
          max_post_count: 5
